name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
    
    - name: CNAME
      run: touch dist/CNAME && echo "syncwatch.live" > dist/CNAME
      
    - uses: crazy-max/ghaction-github-pages@v1
      with:
          target_branch: gh-pages
          build_dir: dist/
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
